# Generated by Django 4.1.1 on 2022-09-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('body_as_markdown', models.BooleanField(default=False, verbose_name='as_markdown')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date of creating')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='date of editing')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
