# Generated by Django 4.1.1 on 2022-10-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_news_preamble'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='create_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='update_date',
            new_name='updated',
        ),
    ]
