# Generated by Django 4.1.1 on 2022-10-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_create_date_news_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('description_as_markdown', models.BooleanField(default=False, verbose_name='as markdown')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='cost')),
                ('cover', models.FilePathField(verbose_name='cover')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.PositiveSmallIntegerField(verbose_name='course')),
                ('num', models.PositiveSmallIntegerField(verbose_name='num')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('description_as_markdown', models.BooleanField(default=False, verbose_name='as markdown')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(max_length=128, verbose_name='name_first')),
                ('name_second', models.CharField(max_length=128, verbose_name='name_second')),
                ('day_birth', models.DateField(verbose_name='day_birth')),
                ('course', models.TextField(null=True, verbose_name='course')),
            ],
        ),
    ]
